services:
  build:
    image: ps2dev/ps2sdk-ports:latest
    working_dir: /src
    volumes:
      - .:/src
    entrypoint: /bin/sh
    command: -c "apk add --no-cache build-base python3 py3-pillow && make"

  shell:
    image: ps2dev/ps2sdk-ports:latest
    working_dir: /src
    volumes:
      - .:/src
    entrypoint: /bin/sh
    stdin_open: true
    tty: true