#!/usr/bin/env python3
"""
Generate a bitmap font atlas from a TTF + a glyph metrics table.

Outputs:
  assets/font_atlas.png   - all printable ASCII glyphs (white on transparent)
  src/font_data.h         - per-glyph atlas rect + advance + draw offset

Glyphs are placed on a COMMON BASELINE so text renders correctly (a 'g'
descends, an 'o' sits on the line, a 'G' rises to cap height). Each glyph
records the vertical offset at which it should be drawn so the runtime
can reproduce the baseline.

Run: python3 tools/genfont.py
"""

import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTF  = os.path.join(ROOT, "assets", "mania.ttf")
ATLAS_PNG = os.path.join(ROOT, "assets", "font_atlas.png")
DATA_H    = os.path.join(ROOT, "src", "font_data.h")

FONT_SIZE = 24
FIRST, LAST = 32, 126
COLS = 16

def main():
    font = ImageFont.truetype(TTF, FONT_SIZE)
    n = LAST - FIRST + 1

    # Font-wide vertical metrics. ascent = pixels above baseline,
    # descent = pixels below. The cell must hold the full line height so
    # every glyph shares one baseline.
    ascent, descent = font.getmetrics()
    line_h = ascent + descent

    tmp = Image.new("RGBA", (1, 1))
    d = ImageDraw.Draw(tmp)

    # Per-glyph horizontal advance + tight bbox (for cell width only).
    metrics = []
    max_w = 0
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        bbox = d.textbbox((0, 0), ch, font=font)
        gw = bbox[2] - bbox[0]
        # advance: how far the pen moves after drawing this char
        adv = d.textlength(ch, font=font)
        if gw <= 0:
            gw = int(adv) if adv > 0 else FONT_SIZE // 3
        metrics.append((code, gw, int(round(adv)), bbox[0]))
        max_w = max(max_w, gw)

    cell_w = max_w + 2
    cell_h = line_h + 2
    rows = (n + COLS - 1) // COLS

    def round_up(x, m): return ((x + m - 1) // m) * m
    atlas_w = round_up(COLS * cell_w, 8)
    atlas_h = round_up(rows * cell_h, 8)

    atlas = Image.new("RGBA", (atlas_w, atlas_h), (0, 0, 0, 0))
    ad = ImageDraw.Draw(atlas)

    entries = []
    for idx, (code, gw, adv, offx) in enumerate(metrics):
        cx = (idx % COLS) * cell_w
        cy = (idx // COLS) * cell_h
        # Draw the glyph at the cell's baseline. PIL's text() with default
        # anchor draws from the top using the font's own ascent, so drawing
        # at (cx, cy) places every glyph on a shared baseline automatically
        # because they all use the same ascent reference. We only shift x to
        # remove left side bearing so glyphs are flush-left in their cell.
        ad.text((cx - offx + 1, cy + 1), chr(code), font=font, fill=(255,255,255,255))
        entries.append((code, cx, cy, cell_w, cell_h, adv + 1))

    # Hard 1-bit alpha: every pixel becomes either fully opaque pure-white
    # or fully transparent. Anti-aliased semi-transparent edge pixels cause
    # colored fringing (stray red dots) when alpha-blended over the menu
    # background on the analog GS output, so we remove them entirely.
    px = atlas.load()
    THRESH = 128
    for yy in range(atlas_h):
        for xx in range(atlas_w):
            r, g, b, a = px[xx, yy]
            if a >= THRESH:
                px[xx, yy] = (255, 255, 255, 255)
            else:
                px[xx, yy] = (0, 0, 0, 0)

    atlas.save(ATLAS_PNG)
    print(f"atlas: {atlas_w}x{atlas_h}, {n} glyphs, cell {cell_w}x{cell_h}, "
          f"ascent {ascent} descent {descent}")

    with open(DATA_H, "w") as f:
        f.write("// AUTO-GENERATED by tools/genfont.py. Do not edit.\n")
        f.write("#ifndef FONT_DATA_H\n#define FONT_DATA_H\n#include <stdint.h>\n\n")
        f.write(f"#define FONT_FIRST_CHAR {FIRST}\n")
        f.write(f"#define FONT_LAST_CHAR {LAST}\n")
        f.write(f"#define FONT_CELL_W {cell_w}\n")
        f.write(f"#define FONT_CELL_H {cell_h}\n\n")
        f.write("typedef struct { uint16_t x, y, w, h, advance; } FontGlyph;\n\n")
        f.write("static const FontGlyph font_glyphs[] = {\n")
        for (code, cx, cy, cw, chh, adv) in entries:
            f.write(f"    {{ {cx}, {cy}, {cw}, {chh}, {adv} }},  // {code}\n")
        f.write("};\n\n#endif\n")
    print(f"wrote {DATA_H}")

if __name__ == "__main__":
    main()