#!/usr/bin/env python3
"""
Embed assets/*.png as raw RGBA8888 C arrays in src/assets_data.{c,h}.

IMPORTANT - power-of-two padding:
The PS2 GS addresses textures using TEX0.TW/TH = log2(width/height). A
320-wide texture would be treated as 512-wide for addressing while the
data is packed 320-wide, misaligning every row (edge artifacts). To avoid
this, each image is padded out to power-of-two dimensions; the original
pixels sit in the top-left. We emit BOTH the padded buffer dimensions
(used for the GSTEXTURE Width/Height so GS addressing matches the data)
and the original dimensions (used as the UV sampling region when drawing).

Output: 32-bit RGBA, one u32 per pixel, row-major, padded W x padded H.
Byte order: byte0=R, byte1=G, byte2=B, byte3=A (GS CT32).

Run: python3 tools/png2c.py
"""
import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
SRC = os.path.join(ROOT, "src")

def cname(filename):
    return os.path.splitext(filename)[0].replace("-", "_").replace(".", "_")

def next_pot(x):
    p = 1
    while p < x:
        p <<= 1
    return p

def main():
    # Only embed PNGs that are actually used as textures. The grid and
    # monoscope are drawn procedurally (grid from code, monoscope from
    # png2rects.py), so embedding them here would just waste space.
    SKIP = {"grid.png", "monoscope.png"}
    pngs = sorted(f for f in os.listdir(ASSETS)
                  if f.lower().endswith(".png") and f not in SKIP)
    if not pngs:
        print(f"No PNGs in {ASSETS}", file=sys.stderr); sys.exit(1)

    h_lines = [
        "// AUTO-GENERATED by tools/png2c.py. Do not edit.",
        "#ifndef ASSETS_DATA_H",
        "#define ASSETS_DATA_H",
        "#include <stdint.h>",
        "",
    ]
    c_lines = [
        "// AUTO-GENERATED by tools/png2c.py. Do not edit.",
        '#include "assets_data.h"',
        "",
    ]

    for png in pngs:
        path = os.path.join(ASSETS, png)
        im = Image.open(path).convert("RGBA")
        w, h = im.size
        name = cname(png)

        # Pad WIDTH to a power of two (height native). The GS addresses
        # textures with TEX0.TW = log2(width), which rounds a 320-wide
        # texture up to 512; if the stored stride doesn't match, rows
        # misalign (left-edge artifacts). Padding width to a power of two
        # keeps stride and addressing consistent. The grid is drawn
        # procedurally and ignores this; monoscope/background use it.
        pw = next_pot(w)
        ph = h
        if (pw, ph) != (w, h):
            padded = Image.new("RGBA", (pw, ph), (0, 0, 0, 0))
            padded.paste(im, (0, 0))
        else:
            padded = im

        pixels = padded.tobytes()  # RGBA, row-major, pw x ph
        words = []
        for i in range(0, len(pixels), 4):
            r, g, b, a = pixels[i], pixels[i+1], pixels[i+2], pixels[i+3]
            u = (a << 24) | (b << 16) | (g << 8) | r
            words.append(f"0x{u:08x}")

        print(f"  {png}: {w}x{h} -> padded {pw}x{ph}, {len(words)} pixels")

        up = name.upper()
        h_lines += [
            f"#define ASSET_{up}_W {pw}",   # padded buffer width (GS texture W)
            f"#define ASSET_{up}_H {ph}",   # padded buffer height (GS texture H)
            f"#define ASSET_{up}_REAL_W {w}",  # visible region width (UV)
            f"#define ASSET_{up}_REAL_H {h}",  # visible region height (UV)
            f"extern const uint32_t asset_{name}_pixels[];",
            "",
        ]

        c_lines += [f"const uint32_t asset_{name}_pixels[] = {{"]
        for i in range(0, len(words), 8):
            c_lines.append("    " + ", ".join(words[i:i+8]) + ",")
        c_lines += ["};", ""]

    h_lines += ["#endif", ""]

    with open(os.path.join(SRC, "assets_data.c"), "w") as f:
        f.write("\n".join(c_lines))
    with open(os.path.join(SRC, "assets_data.h"), "w") as f:
        f.write("\n".join(h_lines))
    print("wrote src/assets_data.c, src/assets_data.h")

if __name__ == "__main__":
    main()