#!/usr/bin/env python3
"""
Convert a 3-color (black/white/red) PNG into a compact list of solid
rectangles, emitted as a C array. Black is treated as the background and
skipped. The PS2 draws each rectangle with gsKit_prim_sprite (a solid
primitive), which - unlike the textured-sprite path - rasterizes the full
width/height with no edge artifacts and needs no padding or coordinate
shifts. Output is pixel-exact with the source PNG.

Greedy rectangle merge: for each uncovered non-black pixel, grow a maximal
same-color rectangle (width first, then height). ~800 rects for the
monoscope, which is trivial for the GS.

Usage: python3 tools/png2rects.py assets/Monoscope320.png monoscope
Writes: src/<name>_rects.h
"""
import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")

# Color codes in the emitted data: 1 = red, 2 = white. Black is skipped.
def classify(p):
    r, g, b = p[0], p[1], p[2]
    if r > 150 and g < 90 and b < 90:  return 1   # red
    if r > 150 and g > 150 and b > 150: return 2  # white
    return 0  # black / background

def decompose(im):
    W, H = im.size
    px = im.load()
    grid = [[classify(px[x, y]) for x in range(W)] for y in range(H)]
    covered = [[False] * W for _ in range(H)]
    rects = []
    for y in range(H):
        for x in range(W):
            if grid[y][x] == 0 or covered[y][x]:
                continue
            cval = grid[y][x]
            w = 1
            while x + w < W and grid[y][x+w] == cval and not covered[y][x+w]:
                w += 1
            h = 1
            while y + h < H and all(grid[y+h][x+i] == cval and not covered[y+h][x+i]
                                    for i in range(w)):
                h += 1
            for yy in range(y, y+h):
                for xx in range(x, x+w):
                    covered[yy][xx] = True
            rects.append((x, y, w, h, cval))
    return rects, W, H

def main():
    if len(sys.argv) != 3:
        print("usage: png2rects.py <png> <name>", file=sys.stderr); sys.exit(1)
    png, name = sys.argv[1], sys.argv[2]
    im = Image.open(png).convert("RGB")
    rects, W, H = decompose(im)
    up = name.upper()
    lines = [
        f"// AUTO-GENERATED by tools/png2rects.py from {os.path.basename(png)}. Do not edit.",
        f"#ifndef {up}_RECTS_H",
        f"#define {up}_RECTS_H",
        "#include <stdint.h>",
        "// Each rect: x, y, w, h, color (1=red, 2=white). Source is WxH at",
        f"// {W}x{H}; scale by the active framebuffer width / {W} at draw time.",
        f"#define {up}_SRC_W {W}",
        f"#define {up}_SRC_H {H}",
        "typedef struct { uint16_t x, y, w, h; uint8_t col; } Rect;",
        f"static const Rect {name}_rects[] = {{",
    ]
    for (x, y, w, h, cval) in rects:
        lines.append(f"    {{{x},{y},{w},{h},{cval}}},")
    lines.append("};")
    lines.append(f"#define {up}_RECT_COUNT ((int)(sizeof({name}_rects)/sizeof({name}_rects[0])))")
    lines.append("#endif")
    out = os.path.join(SRC, f"{name}_rects.h")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(rects)} rects ({W}x{H})")

if __name__ == "__main__":
    main()